version: '3.3'

services:
  kudaki_dashboard:
    build:
      context: .
      dockerfile: ./build/kudaki_dashboard_dockerfile
    container_name: kudaki_dashboard_container
    volumes:
      - kudaki-dashboard-project:/var/www/kudaki-dashboard
  nginx:
    image: nginx:alpine
    container_name: nginx_container
    volumes:
      - kudaki-dashboard-project:/var/www/kudaki-dashboard
      - ./build/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - kudaki_dashboard
    ports:
      - 8080:80
    labels:
      - "traefik.docker.network=${DOCKER_NETWORK}"
      - "traefik.frontend.rule=Host:${REST_SUBDOMAIN}"
      - "traefik.port=${REST_PORT}"

volumes:
  kudaki-dashboard-project:
    external:
      name: kudaki-dashboard-project