version: '3.3'

services:
  kudaki_dashboard:
    image: php:fpm-alpine
    container_name: kudaki_dashboard_container
    volumes:
      - .:kudaki-dashboard-project
      - kudaki-dashboard-project:/var/www/kudaki-dashboard
    entrypoint:
      - php-fpm
  nginx:
    image: nginx:alpine
    container_name: nginx_container
    volumes:
      - kudaki-dashboard-project/build/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - kudaki_dashboard
    ports:
      - 8080:80
    labels:
      - "traefik.docker.network=${DOCKER_NETWORK}"
      - "traefik.rest.frontend.rule=Host:${REST_SUBDOMAIN}"
      - "traefik.rest.port=${REST_PORT}"